from copy import deepcopy
from hashlib import sha256
import json

import pytest

from loopx.control_plane.todos import frontier_revision

from loopx.control_plane.todos.frontier_revision import (
    advancement_frontier_revision_from_index,
    build_advancement_frontier_revision_index,
    selectable_advancement_frontier_revision,
)


def rows():
    return [
        {"todo_id": "todo_a", "task_class": "advancement_task", "status": "open",
         "text": "验证边界", "updated_at": "2026-09-01T00:00:00.000001Z"},
        {"todo_id": "todo_b", "task_class": "advancement_task", "status": "open",
         "text": "Independent work", "excluded_agents": ["worker-a"],
         "updated_at": "2026-09-01T00:00:00.000002Z"},
    ]


@pytest.mark.parametrize("index", [None, [], "invalid", 1, True])
def test_index_adapter_rejects_non_object_typed_response(monkeypatch, index):
    monkeypatch.setattr(frontier_revision, "effect_runtime_result",
                        lambda *_args: {"index": index})
    with pytest.raises(TypeError, match="typed frontier revision response index must be an object"):
        build_advancement_frontier_revision_index(rows())


def test_excluded_unclaimed_work_does_not_rearm_this_agents_frontier():
    before = rows()
    after = deepcopy(before)
    after[1]["priority"] = "P0"
    after[1]["updated_at"] = "2026-09-02T00:00:00Z"
    for source in (before, after):
        direct = selectable_advancement_frontier_revision(source, agent_id="worker-a")
        indexed = advancement_frontier_revision_from_index(
            build_advancement_frontier_revision_index(source), agent_id="worker-a",
        )
        assert direct == indexed
    assert selectable_advancement_frontier_revision(before, agent_id="worker-a") == (
        selectable_advancement_frontier_revision(after, agent_id="worker-a")
    )
    assert selectable_advancement_frontier_revision(before, agent_id="worker-b") != (
        selectable_advancement_frontier_revision(after, agent_id="worker-b")
    )


def test_duplicate_identity_cannot_be_a_complete_frontier():
    source = rows()
    source[1]["todo_id"] = source[0]["todo_id"]
    assert selectable_advancement_frontier_revision(source, agent_id=None) == (None, None, False)


def test_removing_exclusion_rearms_newly_available_work():
    source = rows()
    before = selectable_advancement_frontier_revision(source, agent_id="worker-a")
    source[1].pop("excluded_agents")
    assert selectable_advancement_frontier_revision(source, agent_id="worker-a") != before


def test_v0_codec_preserves_unicode_hash_and_microsecond_ordering():
    # Explicit protocol records, not output generated by the implementation.
    material = [{"status": "open", "task_class": "advancement_task", "text": "边界 🧭",
                 "todo_id": "todo_a"},
                {"status": "done", "task_class": "advancement_task", "todo_id": "todo_b"}]
    encoded = json.dumps(material, ensure_ascii=True, separators=(",", ":"), sort_keys=True)
    expected = "todo_frontier_revision_v0:" + sha256(encoded.encode()).hexdigest()[:24]
    source = [{**material[1], "completed_at": "2026-09-01T08:00:00.000001+08:00"},
              {**material[0], "updated_at": "2026-09-01T00:00:00.000002Z"}]
    assert selectable_advancement_frontier_revision(source, agent_id=None) == (
        expected, "2026-09-01T00:00:00.000002Z", True)


def test_legacy_agent_spelling_in_index_remains_readable():
    source = rows()[:1]
    source[0]["claimed_by"] = "Worker A"
    index = build_advancement_frontier_revision_index(source)
    index["by_agent"][0]["agent_id"] = " Worker\u0085A "
    assert advancement_frontier_revision_from_index(index, agent_id="worker-a") == (
        selectable_advancement_frontier_revision(source, agent_id="Worker A"))


def test_large_frontier_transport_preserves_exact_v0_identity_and_tail_edits():
    material = [{"todo_id": f"todo_{index:04}", "task_class": "advancement_task",
                 "text": "Complete synthetic description " * 40} for index in range(2500)]
    encoded = json.dumps(material, ensure_ascii=True, separators=(",", ":"), sort_keys=True)
    assert len(encoded.encode()) > 2 * 1024 * 1024
    expected = "todo_frontier_revision_v0:" + sha256(encoded.encode()).hexdigest()[:24]
    source = [{**item, "updated_at": "2026-09-01T00:00:00Z"} for item in material]
    assert selectable_advancement_frontier_revision(source, agent_id=None) == (
        expected, "2026-09-01T00:00:00Z", True)
    assert advancement_frontier_revision_from_index(
        build_advancement_frontier_revision_index(source), agent_id=None,
    ) == (expected, "2026-09-01T00:00:00Z", True)
    source[-1]["text"] += " Material edit at the tail."
    assert selectable_advancement_frontier_revision(source, agent_id=None)[0] != expected
