#!/usr/bin/env bash
set -euo pipefail

# Bind all host-facing AI-Coding surfaces to one immutable promoted LoopX release.
# Run as the development user (gany by default), never as root.

RELEASE_DIR=""

usage() {
  cat <<'USAGE'
Usage: ai-coding-bind-runtime.sh --release DIR

Bind Codex/Kiro/Qwen surfaces and helper commands to an already installed,
immutable LoopX release directory. This script never promotes source code; it
only makes host integrations point at the selected stable release.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --release) RELEASE_DIR="${2:?missing release directory}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ -z "$RELEASE_DIR" ]]; then
  echo "--release is required" >&2
  exit 2
fi
if [[ "$(id -u)" -eq 0 ]]; then
  echo "Run runtime binding as the development user, not root." >&2
  exit 1
fi

RELEASE_DIR="$(cd "$RELEASE_DIR" && pwd)"
LOOPX_BIN="$RELEASE_DIR/scripts/loopx"
if [[ ! -x "$LOOPX_BIN" || ! -f "$RELEASE_DIR/release.json" ]]; then
  echo "Not a promoted LoopX release: $RELEASE_DIR" >&2
  exit 1
fi

release_id="$(basename "$RELEASE_DIR")"
config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/ai-coding"
bin_dir="$HOME/.local/bin"
qwen_mcp_root="${AI_CODING_QWEN_MCP_RELEASES_ROOT:-$HOME/.local/share/ai-coding/qwen-mcp/releases}"
qwen_mcp_venv="$qwen_mcp_root/$release_id"

mkdir -p "$config_dir" "$bin_dir" "$qwen_mcp_root" "$HOME/.qwen/skills/loopx"

# Upstream-owned host surfaces are generated from the selected stable release.
CODEX_HOME="${CODEX_HOME:-$HOME/.codex}" \
  "$LOOPX_BIN" slash-commands --install --surface codex >/dev/null
KIRO_HOME="${KIRO_HOME:-$HOME/.kiro}" \
  "$LOOPX_BIN" slash-commands --install --surface kiro-cli >/dev/null

qwen_skill_source="$RELEASE_DIR/skills/ai-coding-qwen-loopx/SKILL.md"
if [[ ! -f "$qwen_skill_source" ]]; then
  echo "Stable release is missing the Qwen LoopX skill: $qwen_skill_source" >&2
  exit 1
fi
install -m 0644 "$qwen_skill_source" "$HOME/.qwen/skills/loopx/SKILL.md"

# Each stable release gets its own Qwen MCP environment. Never editable-install
# /project/loopx here: the worker bridge must not change while 1.N+1 is edited.
if [[ ! -x "$qwen_mcp_venv/bin/python" ]]; then
  python3 -m venv "$qwen_mcp_venv"
fi
"$qwen_mcp_venv/bin/python" -m pip install --disable-pip-version-check --upgrade pip >/dev/null
"$qwen_mcp_venv/bin/python" -m pip install --disable-pip-version-check --upgrade \
  "$RELEASE_DIR" 'mcp==1.28.1' >/dev/null
printf '%s\n' "$release_id" >"$qwen_mcp_venv/.source-release"

if ! command -v qwen >/dev/null 2>&1; then
  echo "qwen is not on PATH; cannot bind stable Qwen MCP runtime" >&2
  exit 1
fi
qwen mcp remove --scope user loopx-ai-coding >/dev/null 2>&1 || true
qwen mcp add --scope user --transport stdio \
  --description "LoopX stable control plane for the AI-Coding Qwen worker lane" \
  loopx-ai-coding "$qwen_mcp_venv/bin/python" -m loopx.extensions.ai_coding.qwen_code_mcp >/dev/null

# Helper entry points follow the promoted release, never the development checkout.
for helper in ai-coding-doctor.sh ai-coding-loopx.sh ai-coding-project-init.sh; do
  if [[ -x "$RELEASE_DIR/scripts/$helper" ]]; then
    name="${helper%.sh}"
    ln -sfn "$RELEASE_DIR/scripts/$helper" "$bin_dir/$name"
  fi
done

source_commit=""
if command -v jq >/dev/null 2>&1; then
  source_commit="$(jq -r '.source.git_commit // empty' "$RELEASE_DIR/release.json" 2>/dev/null || true)"
fi

runtime_tmp="$(mktemp "$config_dir/.runtime.env.XXXXXX")"
cat >"$runtime_tmp" <<EOF_RUNTIME
# Generated by ai-coding-bind-runtime.sh
export AI_CODING_LOOPX_ACTIVE_RELEASE="$RELEASE_DIR"
export AI_CODING_LOOPX_ACTIVE_RELEASE_ID="$release_id"
export AI_CODING_LOOPX_SOURCE_COMMIT="$source_commit"
export AI_CODING_QWEN_MCP_PYTHON="$qwen_mcp_venv/bin/python"
EOF_RUNTIME
chmod 0644 "$runtime_tmp"
mv -f "$runtime_tmp" "$config_dir/runtime.env"

printf 'Bound AI-Coding host surfaces to stable LoopX release: %s\n' "$release_id"
